services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB:revisio
      POSTGRES_USER:postgres
      POSTGRES_PASSWORD:postgres
    ports:
      - "5432:5432"
    restart: always